name = "mathlib-data"
version = "0.1.0"
reservoir = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "lean_scout"
git = "https://github.com/mathlib-initiative/lean_scout.git"
rev = "main"